name: CI

# Trigger the workflow on all pull requests and pushes/merges to main branch
on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cabal:
    name: Cabal tests - ghc ${{ matrix.ghc }} / clash ${{ matrix.clash }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        clash:
          - "1.8.1"
        cabal:
          - "3.10"
        ghc:
          - "9.6.4"

    env:
      clash_version: ${{ matrix.clash }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Use CI specific settings
        run: |
          cp .ci/cabal.project.local .

      - name: Setup CI
        run: |
          cabal v2-freeze
          mv cabal.project.freeze frozen

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ matrix.clash }}-${{ hashFiles('frozen') }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ matrix.clash }}-${{ hashFiles('frozen') }}
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ matrix.clash }}-
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-

      - name: Test
        run: |
          .ci/test_cabal.sh

  documentation:
    name: Haddock Documentation - ghc ${{ matrix.ghc }} / clash ${{ matrix.clash }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        clash:
          - "1.8.1"
        cabal:
          - "3.10"
        ghc:
          - "9.6.4"

    env:
      clash_version: ${{ matrix.clash }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Use CI specific settings
        run: |
          cp .ci/cabal.project.local .

      - build: Build
        run: |
          .ci/build_docs.sh

  linting:
    name: Source code linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Whitespace
        run: |
          .ci/test_whitespace.sh
