resolver: lts-24.36

ghc-options:
  "$locals": -Wall -Wcompat

packages:
  - .
  - hdl-tests

flags:
  clash-cores:
    clash-18: true

extra-deps:
  - clash-prelude-1.8.5
  - clash-lib-1.8.5
  - clash-ghc-1.8.5
  - clash-prelude-hedgehog-1.8.5
  - # clash-testsuite
    git: https://github.com/clash-lang/clash-compiler.git
    commit: '15be98b2f602b9ed23b53d7c77bd1f06ceaa9419' # 1.8 branch @ Sun Apr 12, TODO: replace with v1.8.6
    subdirs:
      - tests
  - git: https://github.com/cchalmers/circuit-notation.git
    commit: '564769c52aa05b90f81bbc898b7af7087d96613d'
  - git: https://github.com/clash-lang/clash-protocols.git
    commit: '9b12c63dabaaa5a8228286bf9406b58c44a48359'
    subdirs:
      - clash-protocols-base
      - clash-protocols
  - hedgehog-1.4@sha256:9860ab34ab3951d9515c71b777d8c9c47610aae7339933e17d26ad9a4afa5618,4754
  - tasty-flaky-0.1.3.1@sha256:9d74c3f776ed69b32db010f5bd5c85b68d03f2d71e8ebb570d894343418ec083,1937

allow-newer: true
allow-newer-deps:
  - clash-protocols
