resolver: lts-23.6

ghc-options:
  "$locals": -Wall -Wcompat

packages:
  - .
  - hdl-tests

flags:
  clash-cores:
    clash-18: true

extra-deps:
  - clash-prelude-1.8.2
  - clash-lib-1.8.2
  - clash-ghc-1.8.2
  - clash-prelude-hedgehog-1.8.2
  - # clash-testsuite
    git: https://github.com/clash-lang/clash-compiler.git
    commit: '49f33ea971eb52b1dbdb7b11dafe0849408001f6' # v1.8.2
    subdirs:
      - tests
  - hedgehog-1.4@sha256:9860ab34ab3951d9515c71b777d8c9c47610aae7339933e17d26ad9a4afa5618,4754
